[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lspscript"
requires-python = ">=3.8"
authors = [
    { name = "Delphy", email = "delphi1024@gmail.com" }
]
dynamic = ["version"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["lspscript*"]

[tool.setuptools.package-data]
"lspscript.token_server" = ["*.js", "*.wasm"]

[tool.setuptools.dynamic]
version = { attr = "lspscript.LSPSCRIPT_VERSION" }

[tool.pytest.ini_options]
testpaths = [
    "."
]
asyncio_mode = "auto"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "uses_external_resources: marks tests which interact with resources outside the LSPScript repo, e.g. external grammar files"
]
