name: Run Unit Tests

on:
  workflow_call:
    inputs:
      runner:
        description: Target runner (e.g. "ubuntu-latest")
        required: true
        type: string

jobs:
  run-unit-tests:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js/npm
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: npm
        cache-dependency-path: "**/package-lock.json"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.8
          3.9
          3.10
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Code Generator Tests and Generate Code for LSP Types
      run: python -m nox -s generate_lsp_types

    - name: Run Unit Tests
      run: python -m nox -p 3.8 3.9 3.10 -s test
