name: Test LSPScript

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to use
        required: true
        type: string
      runner:
        description: Target runner (e.g. "ubuntu-latest")
        required: true
        type: string

jobs:
  test-lspscript:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js/npm
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: npm
        cache-dependency-path: "**/package-lock.json"

    - name: Install mock-server Dependencies
      run: npm ci
      working-directory: mock-server

    - name: Build mock-server
      run: npm run build
      working-directory: mock-server

    - name: Install token-server Dependencies
      run: npm ci
      working-directory: token-server

    - name: Build token-server
      run: npm run build
      working-directory: token-server

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: python -m pytest test
